name: rhosts
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alsa-lib=1.2.14=hb9d3cd8_0
  - anyio=4.5.0=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py38h01eb140_4
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=3.0.0=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - babel=2.16.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - binutils_impl_linux-64=2.44=h4b9a079_2
  - binutils_linux-64=2.44=hc03a8fd_2
  - blas=1.0=openblas
  - bleach=6.1.0=pyhd8ed1ab_0
  - bottleneck=1.3.7=py38ha9d4c09_0
  - brotli-python=1.1.0=py38h17151c0_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h3394656_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.0=py38heb5c249_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - cmake=3.26.3=h077f3f9_0
  - comm=0.2.2=pyhd8ed1ab_0
  - curl=7.88.1=hdc1c0ab_1
  - debugpy=1.8.5=py38h6d02427_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - expat=2.7.1=hecca717_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.14.1=ha770c72_0
  - gcc_impl_linux-64=15.2.0=hcacfade_7
  - gcc_linux-64=15.2.0=h862fb80_12
  - giflib=5.2.2=hd590300_0
  - graphite2=1.3.14=hecca717_2
  - gxx_impl_linux-64=15.2.0=h54ccb8d_7
  - gxx_linux-64=15.2.0=hfaa183a_12
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - h5py=3.8.0=nompi_py38hd5fa8ee_100
  - harfbuzz=11.4.5=h15599e2_0
  - hdf5=1.12.2=nompi_h4df4325_101
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.7=pyh29332c3_1
  - httpx=0.27.2=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_metadata=8.5.0=hd8ed1ab_1
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.12.2=pyh41d4057_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - json5=0.9.25=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py38h578d9bd_0
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter-lsp=2.2.5=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.8.1=pyh31011fe_0
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.14.2=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.2.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.27.3=pyhd8ed1ab_0
  - kernel-headers_linux-64=5.14.0=he073ed8_2
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.20.1=h81ceb04_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h0aef613_1
  - libaec=1.1.4=h3f801dc_0
  - libblas=3.9.0=20_linux64_openblas
  - libcblas=3.9.0=20_linux64_openblas
  - libcups=2.3.3=h36d4200_3
  - libcurl=7.88.1=hdc1c0ab_1
  - libdeflate=1.22=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h69a1729_7
  - libgcc-devel_linux-64=15.2.0=h73f6952_107
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libglib=2.84.4=h77a78f3_0
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.9.0=20_linux64_openblas
  - libnghttp2=1.67.0=had1ee68_0
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libpng=1.6.50=h421ea60_1
  - libsanitizer=15.2.0=hb13aed2_7
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-devel_linux-64=15.2.0=h73f6952_107
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.7.0=he137b08_1
  - libuuid=2.41.2=he9a06e4_0
  - libuv=1.51.0=hb03c661_1
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - make=4.4.1=hb9d3cd8_2
  - markupsafe=2.1.5=py38h01eb140_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mesalib=17.3.9=hdd5ec5b_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - munkres=1.1.4=py_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.4=pyhff2d567_2
  - nbformat=5.10.4=pyhd8ed1ab_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - networkx=3.1=pyhd8ed1ab_0
  - ninja=1.13.1=h171cf75_0
  - notebook=7.2.2=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - numexpr=2.8.4=py38hd2a5715_1
  - numpy=1.24.4=py38h59b608b_0
  - openjdk=11.0.27=h5ddf6bc_0
  - openssl=3.6.0=h26f9b46_0
  - overrides=7.7.0=pyhd8ed1ab_0
  - packaging=25.0=pyh29332c3_1
  - pandas=1.5.3=py38h417a72b_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre2=10.46=h1321c63_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pixman=0.46.4=h54a6638_1
  - pkg-config=0.29.2=h4bc722e_1009
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - pooch=1.8.2=pyhd8ed1ab_0
  - prometheus_client=0.21.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - prompt_toolkit=3.0.48=hd8ed1ab_1
  - psutil=6.0.0=py38hfb59056_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.20=he870216_0
  - python-dateutil=2.9.0post0=py38h06a4308_2
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytz=2024.1=py38h06a4308_0
  - pyyaml=6.0.2=py38h2019614_0
  - pyzmq=26.2.0=py38h6c80b9a_0
  - readline=8.3=hc2a1206_0
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.32.3=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rhash=1.4.3=hd590300_2
  - rpds-py=0.20.0=py38h4005ec7_0
  - scipy=1.10.1=py38h59b608b_3
  - send2trash=1.8.3=pyh0d859eb_0
  - sniffio=1.3.1=pyhd8ed1ab_0
  - soupsieve=2.6=pyhd8ed1ab_0
  - sqlite=3.51.0=h2a70700_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sysroot_linux-64=2.34=h087de78_2
  - terminado=0.18.1=pyh0d859eb_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.4.1=py38hfb59056_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20241003=pyhff2d567_0
  - typing_extensions=4.12.2=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2025b=h78e105d_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=24.8.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xvfbwrapper=0.2.9=pyhd8ed1ab_1005
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h280c20c_3
  - zeromq=4.3.5=h59595ed_1
  - zlib=1.3.1=hb25bd0a_0
  - zstandard=0.23.0=py38h2c38b39_0
  - zstd=1.5.6=hc292b87_0
  - pip:
      - brainspace==0.1.10
      - cechmate==0.0.10
      - contourpy==1.1.1
      - cryptography==46.0.3
      - cycler==0.12.1
      - deprecated==1.3.1
      - exceptiongroup==1.3.0
      - fonttools==4.57.0
      - hopcroftkarp==1.2.4
      - jaraco-classes==3.4.0
      - jeepney==0.9.0
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lxml==6.0.2
      - matplotlib==3.7.5
      - more-itertools==10.5.0
      - neuromaps==0.0.5
      - nibabel==5.2.1
      - nilearn==0.10.4
      - pathspec==0.12.1
      - persim==0.3.8
      - phat==1.5.0
      - pillow==10.4.0
      - pip==25.0.1
      - pyparsing==3.1.4
      - pyqt5==5.15.9
      - pyqt5-qt5==5.15.18
      - pyqt5-sip==12.12.2
      - pysqlite3-binary==0.5.4
      - scikit-build-core==0.11.6
      - scikit-learn==1.3.2
      - secretstorage==3.3.3
      - setuptools==75.3.2
      - six==1.17.0
      - surfplot==0.2.0
      - svgutils==0.3.4
      - threadpoolctl==3.5.0
      - tomli==2.3.0
      - typing-extensions==4.13.2
      - vtk==9.2.6
      - wheel==0.45.1
      - wrapt==2.0.1
      - zipp==3.20.2
prefix: /home/etosato/miniconda3/envs/rhosts
